name: Continous Integration

on: [pull_request, workflow_dispatch]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.
      - name: move to directory and test
        run: |
          cd TASK_2
          npm run test